authorName: Yoel
experimentName: Yoel NNI GDM STOOL TAX 5
trialConcurrency: 4
maxExecDuration: 2h
maxTrialNum: 100
trainingServicePlatform: local

# The path to Search Space
#searchSpacePath: search_space2.json
searchSpacePath: GDM_search_params.json
useAnnotation: false
tuner:
#  builtinTunerName: GridSearch
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
# The path and the running command of trial
trial:
  command: python GDM_NNI.py 6
  codeDir: .
  gpuNum: 1
localConfig:
  # gpuIndices: 1,2
  maxTrialNumPerGpu: 1
  useActiveGpu: false